nome=input ("Digite um funcionário: ")
empresa=input ("Digite a instiuição:")
qtde_funcionarios=int (input("Digite a qtde de funionários: "))
mediaMensalidade=float(input ("Digite a média da mensalidade: "))
print (nome + " trabalha na empresa " + empresa)
print("Possui:", qtde_funcionarios, " funcionarios.")
print("A média da mensalidade é de: " + str(mediaMensalidade))
print("==========Verifique os tipos de dados abaixo: ========")
print("0 tipo de dado da variavel [nome] é: ",type(nome))
print("0 tipo de dado da variavel [empresa] é: ",type(empresa))
print("o tipo de dado da variavel [qtde_funcionarios] é: ",type(qtde_funcionarios))
print("0 tipo de dado da variavel [mediaMensalidade] é: ",type (mediaMensalidade)) 
